# https://vitepress.dev/reference/default-theme-config
nav:
  - text: 主页
    link: /
  - text: 快速入门
    link: /learn/
    activeMatch: /learn/
  - text: 参考文档
    link: /guide/
    activeMatch: /guide/
  - text: WriteUp
    link: /wp/
    activeMatch: /wp/
  - text: 归档
    link: /archive/
    activeMatch: /archive/

sidebar:
  "/learn/":
    - text: 写在前面
      link: /learn/
    - text: 开始
      link: /learn/start

    - text: 各方向入门介绍
      # items:
      #   - text: Web 网络攻防
      #     link: /learn/web
      #   - text: Crypto 密码学
      #     link: /learn/crypto
      #   - text: Reverse 逆向工程
      #     link: /learn/reverse
      #   - text: Pwn 二进制安全
      #     link: /learn/pwn
      #   - text: Misc 杂项
      #     link: /learn/misc

    - text: 参考教程
      # items:
      #   - text: VSCode Python 环境配置
      #     link: /learn/vscode-python
      #   - text: 获取 Linux 发行版
      #     link: /learn/get-linux
      #   - text: WSL 安装教程
      #     link: /learn/install-wsl
      #   - text: 切换软件源
      #     link: /learn/change-software-source
      #   - text: Pwn 环境配置
      #     link: /learn/configure-pwn
      #   - text: Netcat 使用指南
      #     link: /learn/nc

    - text: Q&A
      link: /learn/qa

    - text: 贡献者
      link: /learn/credits

  "/guide/2025/":
    - text: 赛事信息
      link: /guide/2025/
    - text: 宣传
      link: /guide/2025/promotion
    - text: 解题参考
      # items:
      #   - text: Week 1
      #     link: /guide/2025/week1
      #   - text: Week 2
      #     link: /guide/2025/week2
      #   - text: Week 3
      #     link: /guide/2025/week3
      #   - text: Week 4
      #     link: /guide/2025/week4
      #   - text: Week 5
      #     link: /guide/2025/week5

  "/wp/2025/":
    - text: 前言
      link: /wp/2025/
    # - text: Week 1
    #   items:
    #     - text: Pwn
    #       collapsed: true
    #       items:
    #         - text: Real Login
    #           link: /wp/2024/week1/pwn/real-login
    #     - text: Reverse
    #       collapsed: true
    #       items:
    #         - text: begin
    #           link: /wp/2024/week1/reverse/begin
    #     - text: Web
    #       collapsed: true
    #       items:
    #         - text: headach3
    #           link: /wp/2024/week1/web/headach3
    #     - text: Crypto
    #       collapsed: true
    #       items:
    #         - text: xor
    #           link: /wp/2024/week1/crypto/xor
    #     - text: Misc
    #       collapsed: true
    #       items:
    #         - text: decompress
    #           link: /wp/2024/week1/misc/decompress